# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: archlinux

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  archliux_container:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container:
      image: archlinux
      # options: --privileged
    permissions:
      contents: write
    steps:
    
      - uses: actions/checkout@v3
      
      - name: install packages
        run: |
            pacman -Syu --noconfirm
            pacman -S clang spdlog asio openssl xmake unzip --neede --noconfirm
        
      - name: Build
        run: |
            xmake --root -vrDw -y 

      - name: Package
        run: |
            xmake --root pack -f "targz" -y -o ./ 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: hcpp-artifact
            path: ./*.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # draft: true
          # body_path: ${{ github.workspace }}-CHANGELOG.txt  
          files: ./*.tar.gz
          generate_release_notes: true
